# Generated by Django 5.1.4 on 2024-12-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_address_changer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
