# Generated by Django 5.1.4 on 2024-12-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mac_address_changer', '0002_interface_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
